# Generated by Django 3.1.3 on 2020-11-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201128_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_resized',
            field=models.BooleanField(default=False),
        ),
    ]
