# Generated by Django 3.1.3 on 2020-11-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201128_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_1',
            new_name='image',
        ),
    ]
